# Description

Consider the grade records containing five exams for class 01 and class 02, where class 01 has n students and class 02 has m students. Prompt the online judge for a string containing the random seed, the number of students in class01 (n), and the number of students in class02 (m). Create an array of n by 5 for class 01 and an array of m by 5 for class 02 with randomly generated grades between 40 – 100 (100 included). Output the mean and standard deviation with two decimal places for class01 and class02. Output the mean and standard deviation with two decimal places of each exam for all students.

# Input

A string: ‘s, n, m’ where s is the random seed, n is the number of students in class01, and m is the number of students in class02.

# Output

- A n by 5 array (grade records for class01)
- A m by 5 array (grade records for class02)
- A (n+m) by 5 array (grade records for both classes)
- The mean and standard deviation with two decimal places for class01 and class02
- The mean and standard deviation of each exam with two decimal places for all students.

## Reading Input (given)
The following lines of code will help you read in the input string

In [2]:
str_in = input()

In [1]:
# A sample input string for testing
# str_in = '42, 3, 2'
# str_in = '6, 4, 3'

# Main Program (write your main program here and copy and paste them to online judge when you are confident.)

In [1]:
import numpy as np

In [34]:
import numpy as np
str_in = input()
s, n, m = map(int, str_in.split(', '))
# def grades 
def class_grade(s, n, m):
    np.random.seed(s)
    class01_grades = np.random.randint(40, 101, size = (n, 5))
    class02_grades = np.random.randint(40, 101, size = (m, 5)) 
    return class01_grades, class02_grades

class01_grades, class02_grades = class_grade(s, n, m)

class01_grades, class02_grades
print("Grades for class01 are:")
print(class01_grades)
print("Grades for class02 are:")
print(class02_grades)

# combine two class grades
grades_both = np.vstack((class01_grades, class02_grades))
print("Grades for both classes are:")
print(grades_both)

# Function to calculate mean and standard deviation
def calculate_stats(grades):
    mean = np.mean(grades)
    std_dev = np.std(grades)
    return round(mean, 2), round(std_dev, 2)

# Calculate the mean and std for class 01
class01_mean, class01_std = calculate_stats(class01_grades)

# Calculate the mean and std for class 02
class02_mean, class02_std = calculate_stats(class02_grades)

# Calculate the mean and std for each exam across both classes
exam_means = []
exam_stds = []
for i in range(5):
    exam_mean, exam_std = calculate_stats(grades_both[:, i])
    exam_means.append(exam_mean)
    exam_stds.append(exam_std)

# Output the results
print(f"The mean and std for class01 are: {class01_mean:.2f}, {class01_std:.2f}")
print(f"The mean and std for class02 are: {class02_mean:.2f}, {class02_std:.2f}")

for i, (mean, std) in enumerate(zip(exam_means, exam_stds), 1):
    print(f"The mean and std for exam0{i} are: {mean:.2f}, {std:.2f}")

Grades for class01 are:
[[ 78  91  68  54  82]
 [ 47 100  60  78  97]
 [ 58  62  50  50  63]]
Grades for class02 are:
[[92 75 79 63 42]
 [61 92 41 63 83]]
Grades for both classes are:
[[ 78  91  68  54  82]
 [ 47 100  60  78  97]
 [ 58  62  50  50  63]
 [ 92  75  79  63  42]
 [ 61  92  41  63  83]]
The mean and std for class01 are: 69.20, 16.89
The mean and std for class02 are: 69.10, 17.43
The mean and std for exam01 are: 67.20, 15.89
The mean and std for exam02 are: 84.00, 13.67
The mean and std for exam03 are: 59.60, 13.31
The mean and std for exam04 are: 61.60, 9.65
The mean and std for exam05 are: 73.40, 19.06
