# Description
You are to use NumPy's random module with a given seed to generate random integers, ranging from 0 to 120 ($0 \le x < 120$), in a 1D array of size $n$. Adjust the grade records below 40 to 40 and above 100 to 100. Then, change the shape of the 1D array into an $r$ by $c$ 2D array. Last, you are to find those rows with a mean larger than the threshold $m$ and report the 2D array and the sum of those rows. You should report dimension inconsistency if the 1D array cannot be converted into an $r$ by $c$ 2D array. 

# Input
A string containing the following information:
- n (size of the 1D array)</br>
- r (number of rows)</br>
- c (number of columns)</br>
- m (an integer threshold)</br>
- seed (random seed)</br>

# Output
You should report 'Dimension is inconsistent' or 
- the 2D array
- the sum of those rows with a mean larger than m


## Reading Input (given)
The following lines of code will help you read in the input integers

In [1]:
str_in = input()
# str_in = '12, 3, 3, 60, 0'
# str_in = '12, 4, 3, 60, 0'
# str_in = '6, 2, 3, 80, 42'

# Main Program (write your main program here and copy and paste them to online judge when you are confident.)

In [14]:
import numpy as np

str_in = input()
n, r, c, m, seed = map(int, str_in.split(', '))

def matrix():
    if r * c != n:
        print("Dimension is inconsistent")
        return
    
    np.random.seed(seed)
    
    array = np.random.randint(0, 120, size = n)
    array = np.clip(array, 40, 100)
    
    # reshape array
    array_2d = array.reshape(r, c)
    # cal mean
    mean = array_2d.mean(axis = 1)
    # mean > m
    rows_above_threshold = array_2d[mean > m]

    print("The adjusted 2D array")
    print(array_2d)
    if len(rows_above_threshold) > 0:
        print("The sum of those rows with a mean larger than", m)
        print(rows_above_threshold.sum(axis = 1))
    else:
        print("No rows have a mean larger than", m)

matrix()

The adjusted 2D array
[[ 44  47 100]
 [ 64  67  67]
 [100  40  83]
 [ 40 100  40]]
The sum of those rows with a mean larger than 60
[191 198 223]
