# Description

Create a n-by-m matrix containing the even integers from 2 to (n x m)x2. Create a second m-by-2 matrix containing the random integers of 4 or 9 with a given random seed s. Print these two matrices and their matrix multiplication. (hint: for the second matrix, please generate a matrix with a random number of 0 or 1 and use a mask to change them to 4 or 9)

# Input 

n,m,s

# Output

- A n-by-m matrix containing the even integers from 2 through (n x m)x2
- A m-by-2 matrix containing the random integers of 4 or 9 with a given random seed s
- A resulting n-by-2 matrix

## Reading Input (given)
The following lines of code will help you read in the input integer

# Main Program (write your main program here and copy and paste them to online judge when you are confident.)

In [1]:
import numpy as np

In [13]:
str_in = input()
# n by m matrix, random seed s
n, m, s = map(int, str_in.split(','))
# first_matrix
first_matrix = np.arange(2, (n * m) * 2 + 1, 2).reshape(n, m)
print("The first matrix is:")
print(first_matrix)
# second_matrix
np.random.seed(s)
second_matrix = np.random.randint(0, 2, size = (m, 2))
second_matrix = np.where(second_matrix == 0, 4, 9)
print("The second matrix is:")
print(second_matrix)
# The multiplication results of the first and second matrices
result_matrix = np.dot(first_matrix, second_matrix)
print("The multiplication results of the first and second matrices are:")
print(result_matrix)

The first matrix is:
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]
The second matrix is:
[[9 9]
 [4 9]
 [9 4]
 [9 9]
 [4 4]]
The multiplication results of the first and second matrices are:
[[200 190]
 [550 540]
 [900 890]]
